name: Deploy to AWS ECS

on:
  push:
    branches:
      - master # Trigger on the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run unit tests before deployment
      - name: Run Unit Tests
        run: npm run test-unit

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }} # Specify the AWS region here
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 7: Build, tag, and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }} .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 8: Update ECS service with the new image
      - name: Update ECS service with new image
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE_NAME }} --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # Pass the AWS region here

      # Step 9: Delete previous images from ECR (except the latest)
      - name: Delete previous ECR images
        run: |
          # Get the image digest of the latest image
          latest_image_digest=$(aws ecr list-images \
            --repository-name ${{ secrets.ECR_REPOSITORY }} \
            --region ${{ secrets.AWS_REGION }} \
            --filter "tagStatus=TAGGED" \
            --query 'imageIds[?imageTag==`latest`].imageDigest' \
            --output text)

          # Get the list of all image digests except the latest one
          image_digests=$(aws ecr list-images \
            --repository-name ${{ secrets.ECR_REPOSITORY }} \
            --region ${{ secrets.AWS_REGION }} \
            --query 'imageIds[?imageDigest!=`'"$latest_image_digest"'`].imageDigest' \
            --output text)

          # Delete images if they exist
          for digest in $image_digests; do
            aws ecr batch-delete-image --repository-name ${{ secrets.ECR_REPOSITORY }} --region ${{ secrets.AWS_REGION }} --image-ids imageDigest=$digest
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
